name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Testing IfChallenge
      id: testing-ifchallenge
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Testing IfChallenge
        setup-command: ''
        command: mvn test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTING-IFCHALLENGE_RESULTS: "${{steps.testing-ifchallenge.outputs.result}}"
      with:
        runners: testing-ifchallenge
